title: "GSoC’23 Proposal Review | {{Project Name}} ({{Your Name}})"
body:
- type: checkboxes
  id: sharing
  attributes:
    label: I confirm that I set the sharing options of the document to “anyone with the link can comment”.
    options:
        - label: "Yes"
          required: true
- type: dropdown
  id: review-section
  attributes:
    label: Which sections should the reviewer take a look at?
    options:
      - "3.1: WHAT"
      - "3.2: HOW"
  validations:
    required: true
