title: "Installation issue: "
body:
- type: input
  attributes:
    label: Operating System
    description: "What OS are you using?"
  validations:
    required: true
- type: input
  attributes:
    label: RAM size
    description: "What is the RAM size?"
  validations:
    required: true
- type: textarea
    id: steps
    attributes:
      label: Steps followed
      description: "If you encountered this error while following a wiki page, provide a link to the page and specify which step failed. Otherwise, list what steps caused the error. These should be detailed enough for someone else to follow them."
    validations:
      required: true
- type: textarea
    id: Error log
    attributes:
      label: Error log
      description: "Please copy & paste the error log below"
      render: bash
    validations:
      required: true
- type: textarea
    id: steps
    attributes:
      label: Approaches already used to resolve the issue
      description: "What appoaches have you tried to resolve the above isssue?"
    validations:
      required: true
