title: "Installation issue: "
body:
- type: input
  attributes:
    label: Operating System
    description: "What OS are you using?"
  validations:
    required: true
- type: input
  attributes:
    label: RAM size
    description: "What is the RAM size?"
  validations:
    required: true
