title: "Installation issue: "
body:
- type: input
  attributes:
    label: Operating System
    description: "What OS are you using?"
  validations:
    required: true
- type: input
  attributes:
    label: RAM size
    description: "What is the RAM size?"
  validations:
    required: true
- type: textarea
  id: steps
  attributes:
    label: Steps followed
    description: "If you encountered this error while following a wiki page, provide a link to the page and specify which step failed. Otherwise, list what steps caused the error. These should be detailed enough for someone else to follow them."
  validations:
    required: false
- type: textarea
  id: improvements
  attributes:
    label: Top 3 improvements
    description: "What are the top 3 improvements we could make to this project?"
    render: bash
  validations:
    required: true
 
