name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["triage needed", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: A clear and concise description of what you want to happen.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when ...
      value: "A feature request!"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I want ...
      value: "Proposed solution"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I have also considered ...
      value: "Alternatives"
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
      value: "Additional context"
    validations:
      required: false
