name: CLA check

# check if the PR author has signed the CLA

on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependecies
        run: |
          npm install npm
          npm install googleapis@39
          npm install exec-sync
      - name: CLA check
        uses: ./
        id: hello
        env:
          SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
          SHEETS_CRED: ${{ secrets.SHEETS_CRED }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
