name: CLA check

# check if the PR author has signed the CLA

on:
  pull_request_target:
    branches:
      - develop
      - release-*
      - js-*

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prnaeeth Actions
        # You may pin to the exact commit or the version.
        # uses: gp201/oppiabot@66e8d203a8afdd063086e49a7fee2eb0f2120b9c
        uses: gp201/oppiabot@test.19
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
        env:
          SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
          SHEETS_CRED: ${{ secrets.SHEETS_CRED }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

