name: CLA check

# check if the PR author has signed the CLA

on:
  pull_request:
    branches: [ develop ]

jobs:
  cla_check:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth-oauthlib
      - name: execute cla script
        env:
          SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
        run: |
          python cla_check_2.py ${{ github.event.pull_request.user.login }}
