name: Read issue

# this is the corn job
# FLOW:
# cron job -> read codewoner file -> Todo is due today(UTC Based) -> Edit codewoner file (edit.py) -> Create PR

on:
  issues:
    types: [opened, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: [3.8]

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - name: execute py script # run the test.py to get the latest data
      run: |
        python test.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: git commit
      run: | # commit directly to repo
        gh issue list
