name: Revert Wiki Changes Made Through the Web Interface
on:
  gollum

jobs:
  revert:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Push Wiki Changes
        env:
          TEMP_WIKI_FOLDER: temp_wiki
        run: |
          git clone https://github.com/gp201/test-github-actions.wiki.git ${{ env.TEMP_WIKI_FOLDER }}
          rsync -av --delete wiki/ ${{ env.TEMP_WIKI_FOLDER }}/ --exclude .git
          cd ${{ env.TEMP_WIKI_FOLDER }}
          git config --global user.name '${{ github.event.head_commit.author.username }}'
          git config --global user.email '${{ github.event.head_commit.author.username }}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
          git push --force
