name: Revert Wiki Changes Made Through the Web Interface
on:
  gollum

jobs:
  revert:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Push Wiki Changes
        env:
          TEMP_WIKI_FOLDER: temp_wiki
        run: |
          git clone https://github.com/gp201/test-github-actions.wiki.git ${{ env.TEMP_WIKI_FOLDER }}
          cd ${{ env.TEMP_WIKI_FOLDER }}
          git reset --hard backup
          git push -f origin master
